openapi: 3.0.0
info:
  title: Athenai API
  description: |
    API documentation for the Athenai multi-tenant gym management platform.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token for authenticated requests. Contains user context including:
        - User ID, type (platform_admin/tenant_user), and role
        - Gym ID (for tenant users) - extracted from token, not headers
        - All authorization decisions based on JWT claims
    GymIdHeader:
      type: apiKey
      in: header
      name: X-Gym-ID
      description: |
        **ONLY REQUIRED FOR LOGIN ENDPOINT**
        - Used to determine authentication type (platform admin vs tenant user)
        - All other endpoints use gym context from JWT token
        - NOT used for authorization after login

  responses:
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIErrorResponse"
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIErrorResponse"
    Forbidden:
      description: Insufficient permissions
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIErrorResponse"
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIErrorResponse"
    Conflict:
      description: Resource conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIErrorResponse"
    Created:
      description: Resource created successfully
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIResponse"

  schemas:
    LoginRequestDTO:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "admin"
          description: "Username for authentication"
        password:
          type: string
          format: password
          example: "securePassword123"
          description: "User password"

    LoginResponseDTO:
      type: object
      properties:
        access_token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
          description: "JWT access token (expires in 24 hours)"
        refresh_token:
          type: string
          example: "d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6"
          description: "Refresh token (expires in 30 days)"
        user_info:
          $ref: "#/components/schemas/UserInfoDTO"

    UserInfoDTO:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
          description: "User unique identifier"
        username:
          type: string
          example: "johndoe"
          description: "Username"
        email:
          type: string
          format: email
          example: "john@olympusgym.com"
          description: "User email address"
        user_type:
          type: string
          enum: ["platform_admin", "tenant_user"]
          example: "tenant_user"
          description: "Type of user account"
        role:
          type: string
          enum: ["admin", "user", "guest"]
          example: "admin"
          description: "User role within gym (only for tenant users)"
          nullable: true
        gym_id:
          type: string
          format: uuid
          example: "456e7890-e89b-12d3-a456-426614174000"
          description: "Associated gym ID (only for tenant users)"
          nullable: true

    APIResponse:
      type: object
      properties:
        status:
          type: string
          enum: ["success"]
          example: "success"
          description: "Response status"
        message:
          type: string
          example: "Operation completed successfully"
          description: "Human-readable message"
        data:
          description: "Response data (varies by endpoint)"

    APIErrorResponse:
      type: object
      properties:
        status:
          type: string
          enum: ["error"]
          example: "error"
          description: "Response status"
        message:
          type: string
          example: "An error occurred"
          description: "Human-readable error message"
        data:
          type: object
          properties:
            code:
              type: string
              enum:
                [
                  "BAD_REQUEST",
                  "UNAUTHORIZED",
                  "FORBIDDEN",
                  "NOT_FOUND",
                  "CONFLICT",
                  "INTERNAL_ERROR",
                ]
              example: "BAD_REQUEST"
              description: "Error code"
            error:
              type: string
              example: "Invalid input provided"
              description: "Technical error details"
              nullable: true

    TokenValidationResponseDTO:
      type: object
      properties:
        valid:
          type: boolean
          example: true
          description: "Whether the token is valid"
        claims:
          $ref: "#/components/schemas/ClaimsDTO"
        message:
          type: string
          example: "Token validation result"
          description: "Validation result message"

    ClaimsDTO:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        username:
          type: string
          example: "johndoe"
        user_type:
          type: string
          enum: ["platform_admin", "tenant_user"]
          example: "tenant_user"
        gym_id:
          type: string
          format: uuid
          example: "456e7890-e89b-12d3-a456-426614174000"
          nullable: true
        role:
          type: string
          enum: ["admin", "user", "guest"]
          example: "admin"
          nullable: true
        is_active:
          type: boolean
          example: true
        exp:
          type: integer
          format: int64
          example: 1642248000
          description: "Token expiration timestamp"
        iat:
          type: integer
          format: int64
          example: 1642161600
          description: "Token issued at timestamp"

    # User related schemas
    UserCreationDTO:
      type: object
      required:
        - username
        - email
        - password
        - role
      properties:
        username:
          type: string
          example: "john_doe"
        email:
          type: string
          format: email
          example: "john@example.com"
        password:
          type: string
          format: password
          example: "securePassword123"
        role:
          type: string
          enum: [user, admin]
          example: "user"

    UserUpdateDTO:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
          enum: [user, admin]

    UserResponseDTO:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        role:
          type: string
        gymId:
          type: string
        verified:
          type: boolean
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    UserActiveDTO:
      type: object
      required:
        - active
      properties:
        active:
          type: boolean
          example: true

    # Gym related schemas
    GymCreationDTO:
      type: object
      required:
        - name
        - domain
        - admin_username
        - admin_email
        - admin_password
      properties:
        name:
          type: string
          example: "Fitness First"
          description: "Gym name"
        domain:
          type: string
          example: "fitnessfirst"
          description: "Unique domain identifier for the gym"
        admin_username:
          type: string
          example: "admin"
          description: "Username for the gym admin"
        admin_email:
          type: string
          format: email
          example: "admin@fitnessfirst.com"
          description: "Email for the gym admin"
        admin_password:
          type: string
          format: password
          example: "securePassword123"
          description: "Password for the gym admin"

    GymUpdateDTO:
      type: object
      properties:
        name:
          type: string
          example: "New Gym Name"
          description: "Updated gym name"

    GymResponseDTO:
      type: object
      properties:
        gym_id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          example: "Fitness First"
        domain:
          type: string
          example: "fitnessfirst"
        is_active:
          type: boolean
          example: true
        created_at:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          example: "2024-01-15T10:30:00Z"

    GymActivateDTO:
      type: object
      required:
        - active
      properties:
        active:
          type: boolean
          example: true

    RefreshTokenRequestDTO:
      type: object
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string
          example: "d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6"
          description: "Valid refresh token"

paths:
  # Auth routes
  /auth/login:
    $ref: "./paths/auth/login.yaml"

  /auth/refresh:
    $ref: "./paths/auth/refresh.yaml"

  /auth/logout:
    $ref: "./paths/auth/logout.yaml"

  /auth/validate:
    $ref: "./paths/auth/validate.yaml"

  # User routes
  /user:
    $ref: "./paths/user/user.yaml"

  /user/{id}:
    $ref: "./paths/user/user-by-id.yaml"

  /user/username/{username}:
    $ref: "./paths/user/user-by-username.yaml"

  /user/email/{email}:
    $ref: "./paths/user/user-by-email.yaml"

  /user/{id}/verify:
    $ref: "./paths/user/user-verify.yaml"

  /user/{id}/active:
    $ref: "./paths/user/user-active.yaml"

  # Gym routes
  /gym:
    $ref: "./paths/gym/gym.yaml"

  /gym/{id}:
    $ref: "./paths/gym/gym-by-id.yaml"

  /gym/{id}/update:
    $ref: "./paths/gym/gym-update.yaml"

  /gym/domain/{domain}:
    $ref: "./paths/gym/gym-by-domain.yaml"

  /gym/{id}/activate:
    $ref: "./paths/gym/gym-activate.yaml"

  /gym/{id}/deactivate:
    $ref: "./paths/gym/gym-deactivate.yaml"

  /gym/{id}/delete:
    $ref: "./paths/gym/gym-delete.yaml"

  # Template Block routes
  /template-blocks:
    $ref: "./paths/template_block/template_block.yaml"

  /template-blocks/{id}:
    $ref: "./paths/template_block/template_block-by-id.yaml"
