openapi: 3.0.0
info:
  title: Athenai API
  description: API documentation for the Athenai application
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1

components:
  $ref: "./components/index.yaml"

paths:
  # User routes
  /user:
    $ref: "./paths/user/user.yaml"

  /user/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the user
    $ref: "./paths/user/user-by-id.yaml"

  /user/username/{username}:
    parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
        description: The username of the user
    $ref: "./paths/user/user-by-username.yaml"

  /user/email/{email}:
    parameters:
      - name: email
        in: path
        required: true
        schema:
          type: string
          format: email
        description: The email address of the user
    $ref: "./paths/user/user-by-email.yaml"

  /user/{id}/verify:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the user
    $ref: "./paths/user/user-verify.yaml"

  /user/{id}/active:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the user
    $ref: "./paths/user/user-active.yaml"

  # Gym routes
  /gym:
    $ref: "./paths/gym/gym.yaml"

  /gym/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the gym
    $ref: "./paths/gym/gym-by-id.yaml"

  /gym/{id}/update:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the gym
    $ref: "./paths/gym/gym-update.yaml"

  /gym/domain/{domain}:
    parameters:
      - name: domain
        in: path
        required: true
        schema:
          type: string
        description: The unique domain of the gym
    $ref: "./paths/gym/gym-by-domain.yaml"

  /gym/{id}/activate:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the gym
    $ref: "./paths/gym/gym-activate.yaml"

  /gym/{id}/deactivate:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the gym
    $ref: "./paths/gym/gym-deactivate.yaml"

  /gym/{id}/delete:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the gym
    $ref: "./paths/gym/gym-delete.yaml"
