openapi: 3.0.0
info:
  title: Athenai API
  description: API documentation for the Athenai application
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1

components:
  index:
    $ref: "/swagger/components/index.yaml"

paths:
  # User routes
  /user:
    $ref: "/swagger/paths/user/user.yaml"

  /user/{id}:
    $ref: "/swagger/paths/user/user-by-id.yaml"

  /user/username/{username}:
    $ref: "/swagger/paths/user/user-by-username.yaml"

  /user/email/{email}:
    $ref: "/swagger/paths/user/user-by-email.yaml"

  /user/{id}/verify:
    $ref: "/swagger/paths/user/user-verify.yaml"

  /user/{id}/active:
    $ref: "/swagger/paths/user/user-active.yaml"

  # Gym routes
  /gym:
    $ref: "/swagger/paths/gym/gym.yaml"

  /gym/{id}:
    $ref: "/swagger/paths/gym/gym-by-id.yaml"

  /gym/{id}/update:
    $ref: "/swagger/paths/gym/gym-update.yaml"

  /gym/domain/{domain}:
    $ref: "/swagger/paths/gym/gym-by-domain.yaml"

  /gym/{id}/activate:
    $ref: "/swagger/paths/gym/gym-activate.yaml"

  /gym/{id}/deactivate:
    $ref: "/swagger/paths/gym/gym-deactivate.yaml"

  /gym/{id}/delete:
    $ref: "/swagger/paths/gym/gym-delete.yaml"
