openapi: 3.0.0
info:
  title: Athenai API
  description: API documentation for the Athenai application
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1

components:
  $ref: "./components/index.yaml"

paths:
  /users:
    $ref: "./paths/users/users.yaml"
  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the user
    $ref: "./paths/users/users-by-id.yaml"
  /users/username/{username}:
    parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
        description: The username of the user
    $ref: "./paths/users/user-by-username.yaml"

  /users/email/{email}:
    parameters:
      - name: email
        in: path
        required: true
        schema:
          type: string
          format: email
        description: The email address of the user
    $ref: "./paths/users/user-by-email.yaml"

  /users/{id}/verify:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the user
    $ref: "./paths/users/user-verify.yaml"

  /users/{id}/active:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the user
    $ref: "./paths/users/user-active.yaml"

  /gyms:
    $ref: "./paths/gyms/gyms.yaml"

  /gyms/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the gym
    $ref: "./paths/gyms/gym-by-id.yaml"

  /gyms/{id}/update:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the gym
    $ref: "./paths/gyms/gym-update.yaml"

  /gyms/domain/{domain}:
    parameters:
      - name: domain
        in: path
        required: true
        schema:
          type: string
        description: The unique domain of the gym
    $ref: "./paths/gyms/gym-by-domain.yaml"

  /gyms/{id}/activate:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the gym
    $ref: "./paths/gyms/gym-activate.yaml"

  /gyms/{id}/deactivate:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the gym
    $ref: "./paths/gyms/gym-deactivate.yaml"

  /gyms/{id}/delete:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
        description: The unique identifier of the gym
    $ref: "./paths/gyms/gym-delete.yaml"
