root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/athenai.exe"
  cmd = "go build -o ./tmp/athenai.exe ./cmd"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "docs", ".git"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "yaml", "yml", "env"]
  kill_delay = "0s"
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
