# Security schemes
bearerAuth:
  type: http
  scheme: bearer
  bearerFormat: JWT
  description: JWT access token for authentication

GymIdHeader:
  type: apiKey
  in: header
  name: X-Gym-ID
  description: Gym ID for tenant isolation
